// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pi.Api.Data;

#nullable disable

namespace Pi.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220172907_ReplicateGlobalConfigToSuppliers")]
    partial class ReplicateGlobalConfigToSuppliers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pi.Api.Models.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("uq_categoria_nome");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CargoFuncao")
                        .HasColumnType("text")
                        .HasColumnName("cargo_funcao");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Empresa")
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Nit")
                        .HasColumnType("text")
                        .HasColumnName("nit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Pais")
                        .HasColumnType("text")
                        .HasColumnName("pais");

                    b.Property<string>("PessoaContato")
                        .HasColumnType("text")
                        .HasColumnName("pessoa_contato");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Configuracao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataConfig")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_config");

                    b.Property<long?>("IdFornecedor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_fornecedor");

                    b.Property<decimal>("PercentualComissao")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("percentual_comissao");

                    b.Property<decimal>("PercentualGordura")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("percentual_gordura");

                    b.Property<decimal>("ValorDespesasFCA")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_despesas_FCA");

                    b.Property<decimal>("ValorFCAFreteRodFronteira")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_FCA_frete_rod_fronteira");

                    b.Property<decimal>("ValorFOBDespCourier")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_FOB_desp_courier");

                    b.Property<decimal>("ValorFOBDespDespacAduaneiro")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_FOB_desp_despac_aduaneiro");

                    b.Property<decimal>("ValorFOBDespPortRegDoc")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_FOB_desp_port_reg_doc");

                    b.Property<decimal>("ValorFOBFretePortoParanagua")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_FOB_frete_porto_paranagua");

                    b.Property<decimal>("ValorPercImposto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_perc_imposto");

                    b.Property<decimal>("ValorReducaoDolar")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_reducao_dolar");

                    b.HasKey("Id");

                    b.HasIndex("IdFornecedor");

                    b.ToTable("configuracoes", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.ConfiguracoesFreteItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("FlDesconsidera")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_desconsidera");

                    b.Property<long?>("IdFornecedor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_fornecedor");

                    b.Property<long>("IdFreteItem")
                        .HasColumnType("bigint")
                        .HasColumnName("id_frete_item");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdFornecedor");

                    b.HasIndex("IdFreteItem")
                        .HasDatabaseName("ix_configuracoes_frete_item_id_frete_item");

                    b.ToTable("configuracoes_frete_item", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Fornecedor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("uq_fornecedor_cnpj");

                    b.ToTable("fornecedor", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Frete", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("frete", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nome = "FOB"
                        },
                        new
                        {
                            Id = 2L,
                            Nome = "FCA"
                        },
                        new
                        {
                            Id = 3L,
                            Nome = "CIF"
                        });
                });

            modelBuilder.Entity("Pi.Api.Models.FreteItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdFrete")
                        .HasColumnType("bigint")
                        .HasColumnName("id_frete");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdFrete")
                        .HasDatabaseName("ix_frete_item_id_frete");

                    b.ToTable("frete_item", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.ListaPreco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Altura")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("altura");

                    b.Property<DateTimeOffset>("DataListaPreco")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_lista_preco");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<bool>("FlAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_ativo");

                    b.Property<string>("FornecedorLista")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fornecedor_lista");

                    b.Property<decimal?>("G0")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g0");

                    b.Property<decimal?>("G1")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g1");

                    b.Property<decimal?>("G2")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g2");

                    b.Property<decimal?>("G3")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g3");

                    b.Property<decimal?>("G4")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g4");

                    b.Property<decimal?>("G5")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g5");

                    b.Property<decimal?>("G6")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g6");

                    b.Property<decimal?>("G7")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g7");

                    b.Property<decimal?>("G8")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g8");

                    b.Property<decimal>("Largura")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("largura");

                    b.Property<decimal>("M3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("m3");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<decimal>("Profundidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("profundidade");

                    b.Property<string>("TipoPreco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_preco");

                    b.HasKey("Id");

                    b.ToTable("lista_preco", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Marca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("FlAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_ativo");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("bytea")
                        .HasColumnName("imagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("uq_marca_nome");

                    b.ToTable("marca", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Modelo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<long>("IdCategoria")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    b.Property<long>("IdFornecedor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_fornecedor");

                    b.Property<string>("UrlImagem")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_imagem");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdFornecedor");

                    b.ToTable("modelo", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Modulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("altura");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<long>("IdCategoria")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    b.Property<long>("IdFornecedor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_fornecedor");

                    b.Property<long>("IdMarca")
                        .HasColumnType("bigint")
                        .HasColumnName("id_marca");

                    b.Property<decimal>("Largura")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("largura");

                    b.Property<decimal>("M3")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("m3")
                        .HasComputedColumnSql("round((largura * profundidade * altura)::numeric, 2)", true);

                    b.Property<long?>("ModeloId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Pa")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("pa");

                    b.Property<decimal>("Profundidade")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("profundidade");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria")
                        .HasDatabaseName("ix_modulo_id_categoria");

                    b.HasIndex("IdFornecedor")
                        .HasDatabaseName("ix_modulo_id_fornecedor");

                    b.HasIndex("IdMarca")
                        .HasDatabaseName("ix_modulo_id_marca");

                    b.HasIndex("ModeloId");

                    b.ToTable("modulo", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.ModuloTecido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoModuloTecido")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_modulo_tecido");

                    b.Property<DateTime?>("DtUltimaRevisao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_ultima_revisao");

                    b.Property<bool>("FlAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_ativo");

                    b.Property<long>("IdModulo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_modulo");

                    b.Property<long>("IdTecido")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tecido");

                    b.Property<decimal>("ValorTecido")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("valor_tecido");

                    b.HasKey("Id");

                    b.HasIndex("IdModulo")
                        .HasDatabaseName("ix_modulo_tecido_id_modulo");

                    b.HasIndex("IdTecido")
                        .HasDatabaseName("ix_modulo_tecido_id_tecido");

                    b.HasIndex("IdModulo", "IdTecido")
                        .IsUnique()
                        .HasDatabaseName("uq_modulo_tecido_id_modulo_id_tecido");

                    b.ToTable("modulo_tecido", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.PiItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("altura");

                    b.Property<string>("Feet")
                        .HasColumnType("text")
                        .HasColumnName("feet");

                    b.Property<string>("Finishing")
                        .HasColumnType("text")
                        .HasColumnName("finishing");

                    b.Property<long>("IdModuloTecido")
                        .HasColumnType("bigint")
                        .HasColumnName("id_modulo_tecido");

                    b.Property<long>("IdPi")
                        .HasColumnType("bigint")
                        .HasColumnName("id_pi");

                    b.Property<decimal>("Largura")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("largura");

                    b.Property<decimal>("M3")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("m3");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<decimal>("Pa")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("pa");

                    b.Property<decimal>("Profundidade")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("profundidade");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("RateioFrete")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("rateio_frete");

                    b.Property<decimal>("ValorEXW")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_exw");

                    b.Property<decimal>("ValorFinalItemBRL")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_final_item_brl");

                    b.Property<decimal>("ValorFinalItemUSDRisco")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_final_item_usd_risco");

                    b.Property<decimal>("ValorFreteRateadoBRL")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_frete_rateado_brl");

                    b.Property<decimal>("ValorFreteRateadoUSD")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_frete_rateado_usd");

                    b.HasKey("Id");

                    b.HasIndex("IdModuloTecido")
                        .HasDatabaseName("ix_pi_item_id_modulo_tecido");

                    b.HasIndex("IdPi")
                        .HasDatabaseName("ix_pi_item_id_pi");

                    b.ToTable("pi_item", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.ProformaInvoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CotacaoAtualUSD")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cotacao_atual_usd");

                    b.Property<decimal>("CotacaoRisco")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cotacao_risco");

                    b.Property<DateTimeOffset>("DataPi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pi");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<long>("IdConfiguracoes")
                        .HasColumnType("bigint")
                        .HasColumnName("id_configuracoes");

                    b.Property<long?>("IdFornecedor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_fornecedor");

                    b.Property<long>("IdFrete")
                        .HasColumnType("bigint")
                        .HasColumnName("id_frete");

                    b.Property<string>("PiSequencia")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("pi_sequencia");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefixo");

                    b.Property<decimal>("ValorTecido")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_tecido");

                    b.Property<decimal>("ValorTotalFreteBRL")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total_frete_brl");

                    b.Property<decimal>("ValorTotalFreteUSD")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total_frete_usd");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_pi_id_cliente");

                    b.HasIndex("IdConfiguracoes")
                        .HasDatabaseName("ix_pi_id_configuracoes");

                    b.HasIndex("IdFornecedor");

                    b.HasIndex("IdFrete")
                        .HasDatabaseName("ix_pi_id_frete");

                    b.HasIndex("PiSequencia")
                        .HasDatabaseName("ix_pi_sequencia");

                    b.ToTable("pi", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Tecido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("uq_tecido_nome");

                    b.ToTable("tecido", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.VersaoSistema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("versao");

                    b.HasKey("Id");

                    b.ToTable("versao_sistema");
                });

            modelBuilder.Entity("Pi.Api.Models.Configuracao", b =>
                {
                    b.HasOne("Pi.Api.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("IdFornecedor");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Pi.Api.Models.ConfiguracoesFreteItem", b =>
                {
                    b.HasOne("Pi.Api.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("IdFornecedor");

                    b.HasOne("Pi.Api.Models.FreteItem", "FreteItem")
                        .WithMany("ConfiguracoesFreteItens")
                        .HasForeignKey("IdFreteItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("FreteItem");
                });

            modelBuilder.Entity("Pi.Api.Models.FreteItem", b =>
                {
                    b.HasOne("Pi.Api.Models.Frete", "Frete")
                        .WithMany("FreteItens")
                        .HasForeignKey("IdFrete")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frete");
                });

            modelBuilder.Entity("Pi.Api.Models.Modelo", b =>
                {
                    b.HasOne("Pi.Api.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pi.Api.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Pi.Api.Models.Modulo", b =>
                {
                    b.HasOne("Pi.Api.Models.Categoria", "Categoria")
                        .WithMany("Modulos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pi.Api.Models.Fornecedor", "Fornecedor")
                        .WithMany("Modulos")
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pi.Api.Models.Marca", "Marca")
                        .WithMany("Modulos")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pi.Api.Models.Modelo", null)
                        .WithMany("Modulos")
                        .HasForeignKey("ModeloId");

                    b.Navigation("Categoria");

                    b.Navigation("Fornecedor");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Pi.Api.Models.ModuloTecido", b =>
                {
                    b.HasOne("Pi.Api.Models.Modulo", "Modulo")
                        .WithMany("ModulosTecidos")
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pi.Api.Models.Tecido", "Tecido")
                        .WithMany("ModulosTecidos")
                        .HasForeignKey("IdTecido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Tecido");
                });

            modelBuilder.Entity("Pi.Api.Models.PiItem", b =>
                {
                    b.HasOne("Pi.Api.Models.ModuloTecido", "ModuloTecido")
                        .WithMany()
                        .HasForeignKey("IdModuloTecido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pi.Api.Models.ProformaInvoice", "Pi")
                        .WithMany("PiItens")
                        .HasForeignKey("IdPi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuloTecido");

                    b.Navigation("Pi");
                });

            modelBuilder.Entity("Pi.Api.Models.ProformaInvoice", b =>
                {
                    b.HasOne("Pi.Api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pi.Api.Models.Configuracao", "Configuracoes")
                        .WithMany()
                        .HasForeignKey("IdConfiguracoes")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pi.Api.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("IdFornecedor");

                    b.HasOne("Pi.Api.Models.Frete", "Frete")
                        .WithMany("Pis")
                        .HasForeignKey("IdFrete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Configuracoes");

                    b.Navigation("Fornecedor");

                    b.Navigation("Frete");
                });

            modelBuilder.Entity("Pi.Api.Models.Categoria", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("Pi.Api.Models.Fornecedor", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("Pi.Api.Models.Frete", b =>
                {
                    b.Navigation("FreteItens");

                    b.Navigation("Pis");
                });

            modelBuilder.Entity("Pi.Api.Models.FreteItem", b =>
                {
                    b.Navigation("ConfiguracoesFreteItens");
                });

            modelBuilder.Entity("Pi.Api.Models.Marca", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("Pi.Api.Models.Modelo", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("Pi.Api.Models.Modulo", b =>
                {
                    b.Navigation("ModulosTecidos");
                });

            modelBuilder.Entity("Pi.Api.Models.ProformaInvoice", b =>
                {
                    b.Navigation("PiItens");
                });

            modelBuilder.Entity("Pi.Api.Models.Tecido", b =>
                {
                    b.Navigation("ModulosTecidos");
                });
#pragma warning restore 612, 618
        }
    }
}
