// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pi.Api.Data;

#nullable disable

namespace Pi.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120233028_AddLookupTables")]
    partial class AddLookupTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pi.Api.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categoria");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000001"),
                            Nome = "Estofado"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000002"),
                            Nome = "Cadeira"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000003"),
                            Nome = "Chaise"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000004"),
                            Nome = "Poltrona"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000005"),
                            Nome = "Cama"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000006"),
                            Nome = "Almofada"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000007"),
                            Nome = "Puff"
                        });
                });

            modelBuilder.Entity("Pi.Api.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CargoFuncao")
                        .HasColumnType("text")
                        .HasColumnName("cargo_funcao");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Empresa")
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Pais")
                        .HasColumnType("text")
                        .HasColumnName("pais");

                    b.Property<string>("PessoaContato")
                        .HasColumnType("text")
                        .HasColumnName("pessoa_contato");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Modelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("modelo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2a2b2c2-1a1b-4c4d-9f22-000000000101"),
                            Nome = "Daybed fixa (144)"
                        },
                        new
                        {
                            Id = new Guid("d2a2b2c2-1a1b-4c4d-9f22-000000000102"),
                            Nome = "Daybed giratória (144)"
                        },
                        new
                        {
                            Id = new Guid("d2a2b2c2-1a1b-4c4d-9f22-000000000103"),
                            Nome = "Daybed fixa (164)"
                        },
                        new
                        {
                            Id = new Guid("d2a2b2c2-1a1b-4c4d-9f22-000000000104"),
                            Nome = "Daybed giratória (164)"
                        });
                });

            modelBuilder.Entity("Pi.Api.Models.PiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataPi")
                        .HasColumnType("date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPreco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalBrl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UsdRate")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("UsdRateAtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsdRateFonte")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("pis", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.PiSequencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefixo");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("integer")
                        .HasColumnName("ultimo_numero");

                    b.HasKey("Id");

                    b.HasIndex("Prefixo", "Ano")
                        .IsUnique()
                        .HasDatabaseName("uq_pi_sequencias_prefixo_ano");

                    b.ToTable("pi_sequencias", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Tecido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("tecido");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000201"),
                            Nome = "G0"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000202"),
                            Nome = "G1"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000203"),
                            Nome = "G2"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000204"),
                            Nome = "G3"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000205"),
                            Nome = "G4"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000206"),
                            Nome = "G5"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000207"),
                            Nome = "G6"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000208"),
                            Nome = "G7"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000209"),
                            Nome = "G8"
                        });
                });

            modelBuilder.Entity("Pi.Api.Models.PiModel", b =>
                {
                    b.HasOne("Pi.Api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
