// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pi.Api.Data;

#nullable disable

namespace Pi.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pi.Api.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categoria");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000001"),
                            Nome = "Estofado"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000002"),
                            Nome = "Cadeira"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000003"),
                            Nome = "Chaise"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000004"),
                            Nome = "Poltrona"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000005"),
                            Nome = "Cama"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000006"),
                            Nome = "Almofada"
                        },
                        new
                        {
                            Id = new Guid("c5e1c1b1-8b2c-4b2f-9f11-000000000007"),
                            Nome = "Puff"
                        });
                });

            modelBuilder.Entity("Pi.Api.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CargoFuncao")
                        .HasColumnType("text")
                        .HasColumnName("cargo_funcao");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Empresa")
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Pais")
                        .HasColumnType("text")
                        .HasColumnName("pais");

                    b.Property<string>("PessoaContato")
                        .HasColumnType("text")
                        .HasColumnName("pessoa_contato");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.ListaPreco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Altura")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("altura");

                    b.Property<DateTimeOffset>("DataListaPreco")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_lista_preco");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<bool>("FlAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_ativo");

                    b.Property<string>("FornecedorLista")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fornecedor_lista");

                    b.Property<decimal?>("G0")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g0");

                    b.Property<decimal?>("G1")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g1");

                    b.Property<decimal?>("G2")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g2");

                    b.Property<decimal?>("G3")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g3");

                    b.Property<decimal?>("G4")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g4");

                    b.Property<decimal?>("G5")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g5");

                    b.Property<decimal?>("G6")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g6");

                    b.Property<decimal?>("G7")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g7");

                    b.Property<decimal?>("G8")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("g8");

                    b.Property<decimal>("Largura")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("largura");

                    b.Property<decimal>("M3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("m3");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<decimal>("Profundidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("profundidade");

                    b.Property<string>("TipoPreco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_preco");

                    b.HasKey("Id");

                    b.ToTable("lista_preco", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Modelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("modelo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2a2b2c2-1a1b-4c4d-9f22-000000000101"),
                            Nome = "Daybed fixa (144)"
                        },
                        new
                        {
                            Id = new Guid("d2a2b2c2-1a1b-4c4d-9f22-000000000102"),
                            Nome = "Daybed giratória (144)"
                        },
                        new
                        {
                            Id = new Guid("d2a2b2c2-1a1b-4c4d-9f22-000000000103"),
                            Nome = "Daybed fixa (164)"
                        },
                        new
                        {
                            Id = new Guid("d2a2b2c2-1a1b-4c4d-9f22-000000000104"),
                            Nome = "Daybed giratória (164)"
                        });
                });

            modelBuilder.Entity("Pi.Api.Models.PiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataPi")
                        .HasColumnType("date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPreco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalBrl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UsdRate")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("UsdRateAtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsdRateFonte")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("pis", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.PiSequencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefixo");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("integer")
                        .HasColumnName("ultimo_numero");

                    b.HasKey("Id");

                    b.HasIndex("Prefixo", "Ano")
                        .IsUnique()
                        .HasDatabaseName("uq_pi_sequencias_prefixo_ano");

                    b.ToTable("pi_sequencias", (string)null);
                });

            modelBuilder.Entity("Pi.Api.Models.Tecido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("tecido");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000201"),
                            Nome = "G0"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000202"),
                            Nome = "G1"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000203"),
                            Nome = "G2"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000204"),
                            Nome = "G3"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000205"),
                            Nome = "G4"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000206"),
                            Nome = "G5"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000207"),
                            Nome = "G6"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000208"),
                            Nome = "G7"
                        },
                        new
                        {
                            Id = new Guid("e3b3c3d3-2b2c-4d4e-9f33-000000000209"),
                            Nome = "G8"
                        });
                });

            modelBuilder.Entity("Pi.Api.Models.PiModel", b =>
                {
                    b.HasOne("Pi.Api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
