using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pi.Api.Data;
using Pi.Api.Models;

namespace Pi.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class ConfiguracoesController : ControllerBase
{
    private readonly AppDbContext _context;

    public ConfiguracoesController(AppDbContext context)
    {
        _context = context;
    }

    [HttpGet]
    public async Task<ActionResult<List<Configuracao>>> GetConfiguracoes()
    {
        // Retorna a lista completa ordenada por data decrescente (mais recente primeiro)
        return await _context.Configuracoes
            .OrderByDescending(c => c.DataConfig)
            .ToListAsync();
    }

    [HttpGet("latest")]
    public async Task<ActionResult<Configuracao>> GetLatestConfiguracao()
    {
        var config = await _context.Configuracoes
            .OrderByDescending(c => c.DataConfig)
            .FirstOrDefaultAsync();

        if (config == null)
        {
            return NotFound("Nenhuma configuração encontrada.");
        }

        return config;
    }

    [HttpGet("{id}")]
    public async Task<ActionResult<Configuracao>> GetConfiguracao(long id)
    {
        var config = await _context.Configuracoes.FindAsync(id);

        if (config == null)
        {
            return NotFound();
        }

        return config;
    }

    [HttpPost]
    public async Task<ActionResult<Configuracao>> CreateConfiguracao(Configuracao config)
    {
        // Force ID to 0 to ensure new record
        config.Id = 0;
        config.DataConfig = DateTime.UtcNow; // Always set current time for new config

        _context.Configuracoes.Add(config);
        await _context.SaveChangesAsync();

        return CreatedAtAction(nameof(GetConfiguracao), new { id = config.Id }, config);
    }
    
    // Opcional: Update (PUT)
    // Se a regra é "sempre criar um histórico", talvez não devêssemos ter PUT.
    // Mas para correções rápidas na mesma configuração, pode ser útil.
    [HttpPut("{id}")]
    public async Task<IActionResult> UpdateConfiguracao(long id, Configuracao config)
    {
        if (id != config.Id)
        {
            return BadRequest();
        }

        _context.Entry(config).State = EntityState.Modified;

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!ConfiguracaoExists(id))
            {
                return NotFound();
            }
            else
            {
                throw;
            }
        }

        return NoContent();
    }

    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteConfiguracao(long id)
    {
        var config = await _context.Configuracoes.FindAsync(id);
        if (config == null)
        {
            return NotFound();
        }

        _context.Configuracoes.Remove(config);
        await _context.SaveChangesAsync();

        return NoContent();
    }

    private bool ConfiguracaoExists(long id)
    {
        return (_context.Configuracoes?.Any(e => e.Id == id)).GetValueOrDefault();
    }

    [HttpPost("fix-sequences")]
    public async Task<IActionResult> FixSequences()
    {
        try 
        {
            async Task ResetSeq(string table, string seq)
            {
                // EF Core SqlQueryRaw with primitive types often expects column named "Value"
                var max = await _context.Database.SqlQueryRaw<long?>($"SELECT MAX(id) as \"Value\" FROM {table}").FirstOrDefaultAsync() ?? 0;
                var next = max + 1;
                Console.WriteLine($"[FixSequences] {table}: Max ID={max}, Restarting identity to {next}");
                
                // For Identity Columns (GENERATED BY DEFAULT AS IDENTITY)
                await _context.Database.ExecuteSqlRawAsync($"ALTER TABLE {table} ALTER COLUMN id RESTART WITH {next}");
                Console.WriteLine($"[FixSequences] {table} identity restart complete.");
            }

            // Sequence name arg is unused now but kept for signature compatibility if wanted, or just ignore
            await ResetSeq("frete_item", ""); 
            await ResetSeq("configuracoes_frete_item", "");

            return Ok("Sequences reset (hardcoded names)");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[FixSequences] ERROR: {ex.Message}");
            return StatusCode(500, ex.Message);
        }
    }
}
