INSERT INTO marca(id, descricao) VALUES (1, 'Affair');
INSERT INTO marca(id, descricao) VALUES (2, 'Akira');
INSERT INTO marca(id, descricao) VALUES (3, 'Alma');
INSERT INTO marca(id, descricao) VALUES (4, 'Amarilis');
INSERT INTO marca(id, descricao) VALUES (5, 'Aragon');
INSERT INTO marca(id, descricao) VALUES (6, 'Aurora');
INSERT INTO marca(id, descricao) VALUES (7, 'Barolo');
INSERT INTO marca(id, descricao) VALUES (8, 'Benito');
INSERT INTO marca(id, descricao) VALUES (9, 'Blade');
INSERT INTO marca(id, descricao) VALUES (10, 'Bonet');
INSERT INTO marca(id, descricao) VALUES (11, 'Boris');
INSERT INTO marca(id, descricao) VALUES (12, 'Boris Rt');
INSERT INTO marca(id, descricao) VALUES (13, 'Bosch');
INSERT INTO marca(id, descricao) VALUES (14, 'Brunello');
INSERT INTO marca(id, descricao) VALUES (15, 'Burke');
INSERT INTO marca(id, descricao) VALUES (16, 'Camaleão');
INSERT INTO marca(id, descricao) VALUES (17, 'Camus');
INSERT INTO marca(id, descricao) VALUES (18, 'Carybé');
INSERT INTO marca(id, descricao) VALUES (19, 'Chandon');
INSERT INTO marca(id, descricao) VALUES (20, 'Dante');
INSERT INTO marca(id, descricao) VALUES (21, 'Delphi');
INSERT INTO marca(id, descricao) VALUES (22, 'Desire');
INSERT INTO marca(id, descricao) VALUES (23, 'Dream Home');
INSERT INTO marca(id, descricao) VALUES (24, 'Dream Living');
INSERT INTO marca(id, descricao) VALUES (25, 'Duccio');
INSERT INTO marca(id, descricao) VALUES (26, 'Duchamp');
INSERT INTO marca(id, descricao) VALUES (27, 'Egon');
INSERT INTO marca(id, descricao) VALUES (28, 'Enaga');
INSERT INTO marca(id, descricao) VALUES (29, 'Garzon');
INSERT INTO marca(id, descricao) VALUES (30, 'Gaspar');
INSERT INTO marca(id, descricao) VALUES (31, 'Gema');
INSERT INTO marca(id, descricao) VALUES (32, 'Gentile');
INSERT INTO marca(id, descricao) VALUES (33, 'Grant');
INSERT INTO marca(id, descricao) VALUES (34, 'Grou');
INSERT INTO marca(id, descricao) VALUES (35, 'Gunter');
INSERT INTO marca(id, descricao) VALUES (36, 'Hassan');
INSERT INTO marca(id, descricao) VALUES (37, 'Ikigai');
INSERT INTO marca(id, descricao) VALUES (38, 'Imperio');
INSERT INTO marca(id, descricao) VALUES (39, 'Jacob');
INSERT INTO marca(id, descricao) VALUES (40, 'Join');
INSERT INTO marca(id, descricao) VALUES (41, 'Kaori');
INSERT INTO marca(id, descricao) VALUES (42, 'Katana');
INSERT INTO marca(id, descricao) VALUES (43, 'Keiko');
INSERT INTO marca(id, descricao) VALUES (44, 'Kent');
INSERT INTO marca(id, descricao) VALUES (45, 'Kimi');
INSERT INTO marca(id, descricao) VALUES (46, 'Klimt');
INSERT INTO marca(id, descricao) VALUES (47, 'Klimt Capa');
INSERT INTO marca(id, descricao) VALUES (48, 'Larimar');
INSERT INTO marca(id, descricao) VALUES (49, 'Laser');
INSERT INTO marca(id, descricao) VALUES (50, 'Latitude');
INSERT INTO marca(id, descricao) VALUES (51, 'Leblon');
INSERT INTO marca(id, descricao) VALUES (52, 'Letto');
INSERT INTO marca(id, descricao) VALUES (53, 'Lirio');
INSERT INTO marca(id, descricao) VALUES (54, 'Little');
INSERT INTO marca(id, descricao) VALUES (55, 'Love');
INSERT INTO marca(id, descricao) VALUES (56, 'Malta');
INSERT INTO marca(id, descricao) VALUES (57, 'Manhattan');
INSERT INTO marca(id, descricao) VALUES (58, 'Masip');
INSERT INTO marca(id, descricao) VALUES (59, 'Matsu');
INSERT INTO marca(id, descricao) VALUES (60, 'Matteo');
INSERT INTO marca(id, descricao) VALUES (61, 'Mendonza');
INSERT INTO marca(id, descricao) VALUES (62, 'Merlot');
INSERT INTO marca(id, descricao) VALUES (63, 'Miolo');
INSERT INTO marca(id, descricao) VALUES (64, 'Miro');
INSERT INTO marca(id, descricao) VALUES (65, 'Natasha');
INSERT INTO marca(id, descricao) VALUES (66, 'Nery');
INSERT INTO marca(id, descricao) VALUES (67, 'Noble');
INSERT INTO marca(id, descricao) VALUES (68, 'Noir');
INSERT INTO marca(id, descricao) VALUES (69, 'Oca');
INSERT INTO marca(id, descricao) VALUES (70, 'Paul');
INSERT INTO marca(id, descricao) VALUES (71, 'Picasso');
INSERT INTO marca(id, descricao) VALUES (72, 'Portinari');
INSERT INTO marca(id, descricao) VALUES (73, 'Retmoon');
INSERT INTO marca(id, descricao) VALUES (74, 'Retmoon Flex');
INSERT INTO marca(id, descricao) VALUES (75, 'Rolfe');
INSERT INTO marca(id, descricao) VALUES (76, 'Romano (Base Metal)');
INSERT INTO marca(id, descricao) VALUES (77, 'Romano (Base Madeira)');
INSERT INTO marca(id, descricao) VALUES (78, 'Sense');
INSERT INTO marca(id, descricao) VALUES (79, 'Silvester');
INSERT INTO marca(id, descricao) VALUES (80, 'Sollo');
INSERT INTO marca(id, descricao) VALUES (81, 'Square');
INSERT INTO marca(id, descricao) VALUES (82, 'Tannat');
INSERT INTO marca(id, descricao) VALUES (83, 'Tijuca');
INSERT INTO marca(id, descricao) VALUES (84, 'Torino');
INSERT INTO marca(id, descricao) VALUES (85, 'Twisty');
INSERT INTO marca(id, descricao) VALUES (86, 'Uchiwa');
INSERT INTO marca(id, descricao) VALUES (87, 'Unity');
INSERT INTO marca(id, descricao) VALUES (88, 'Velvet');
INSERT INTO marca(id, descricao) VALUES (89, 'Vision');
INSERT INTO marca(id, descricao) VALUES (90, 'Vuoto');
INSERT INTO marca(id, descricao) VALUES (91, 'Wall');
INSERT INTO marca(id, descricao) VALUES (92, 'Williams');
INSERT INTO marca(id, descricao) VALUES (93, 'Zara');
INSERT INTO marca(id, descricao) VALUES (94, 'Zoe');
INSERT INTO marca(id, descricao) VALUES (95, 'Bold');
INSERT INTO marca(id, descricao) VALUES (96, 'Fluf');
INSERT INTO marca(id, descricao) VALUES (97, 'Yoshi');
INSERT INTO marca(id, descricao) VALUES (98, 'Maço');
INSERT INTO marca(id, descricao) VALUES (99, 'Mizuki');
INSERT INTO marca(id, descricao) VALUES (100, 'Oleg');
INSERT INTO marca(id, descricao) VALUES (101, 'Soft');
INSERT INTO marca(id, descricao) VALUES (102, 'Daybed Flores');
INSERT INTO marca(id, descricao) VALUES (103, 'Alvorada');
INSERT INTO marca(id, descricao) VALUES (104, 'Arraia');
INSERT INTO marca(id, descricao) VALUES (105, 'Ask');
INSERT INTO marca(id, descricao) VALUES (106, 'Bea');
INSERT INTO marca(id, descricao) VALUES (107, 'Bojo');
INSERT INTO marca(id, descricao) VALUES (108, 'Bonsai');
INSERT INTO marca(id, descricao) VALUES (109, 'Bouza');
INSERT INTO marca(id, descricao) VALUES (110, 'Bule');
INSERT INTO marca(id, descricao) VALUES (111, 'Check');
INSERT INTO marca(id, descricao) VALUES (112, 'Circus');
INSERT INTO marca(id, descricao) VALUES (113, 'Copan');
INSERT INTO marca(id, descricao) VALUES (114, 'Doncella');
INSERT INTO marca(id, descricao) VALUES (115, 'Elsa');
INSERT INTO marca(id, descricao) VALUES (116, 'Ema');
INSERT INTO marca(id, descricao) VALUES (117, 'Fast');
INSERT INTO marca(id, descricao) VALUES (118, 'Fuji Assimétrica');
INSERT INTO marca(id, descricao) VALUES (119, 'Giotto');
INSERT INTO marca(id, descricao) VALUES (120, 'Hals');
INSERT INTO marca(id, descricao) VALUES (121, 'Host');
INSERT INTO marca(id, descricao) VALUES (122, 'Icon');
INSERT INTO marca(id, descricao) VALUES (123, 'Leda');
INSERT INTO marca(id, descricao) VALUES (124, 'Legno');
INSERT INTO marca(id, descricao) VALUES (125, 'Life');
INSERT INTO marca(id, descricao) VALUES (126, 'Login');
INSERT INTO marca(id, descricao) VALUES (127, 'Luy');
INSERT INTO marca(id, descricao) VALUES (128, 'Luz');
INSERT INTO marca(id, descricao) VALUES (129, 'Mica');
INSERT INTO marca(id, descricao) VALUES (130, 'Morone');
INSERT INTO marca(id, descricao) VALUES (131, 'Mush');
INSERT INTO marca(id, descricao) VALUES (132, 'Nami');
INSERT INTO marca(id, descricao) VALUES (133, 'Nemo');
INSERT INTO marca(id, descricao) VALUES (134, 'Noko');
INSERT INTO marca(id, descricao) VALUES (135, 'Nube Fixa');
INSERT INTO marca(id, descricao) VALUES (136, 'Nube Giratória');
INSERT INTO marca(id, descricao) VALUES (137, 'Nubia');
INSERT INTO marca(id, descricao) VALUES (138, 'Omega');
INSERT INTO marca(id, descricao) VALUES (139, 'Pinot');
INSERT INTO marca(id, descricao) VALUES (140, 'Poti');
INSERT INTO marca(id, descricao) VALUES (141, 'Rhode');
INSERT INTO marca(id, descricao) VALUES (142, 'Stella');
INSERT INTO marca(id, descricao) VALUES (143, 'Sugoi');
INSERT INTO marca(id, descricao) VALUES (144, 'Syrah');
INSERT INTO marca(id, descricao) VALUES (145, 'Taro');
INSERT INTO marca(id, descricao) VALUES (146, 'Tóquio');
INSERT INTO marca(id, descricao) VALUES (147, 'Tord');
INSERT INTO marca(id, descricao) VALUES (148, 'Tsuru');
INSERT INTO marca(id, descricao) VALUES (149, 'Volo');
INSERT INTO marca(id, descricao) VALUES (150, 'Smile');
INSERT INTO marca(id, descricao) VALUES (151, 'Haru');
INSERT INTO marca(id, descricao) VALUES (152, 'Kaze');
INSERT INTO marca(id, descricao) VALUES (153, 'Kazumi');
INSERT INTO marca(id, descricao) VALUES (154, 'Yumi');
INSERT INTO marca(id, descricao) VALUES (155, 'Almofadas De Rim');
INSERT INTO marca(id, descricao) VALUES (156, 'Almofadas Decorativas C/ Borda');
INSERT INTO marca(id, descricao) VALUES (157, 'Almofadas Decorativas S/ Borda');
INSERT INTO marca(id, descricao) VALUES (158, 'Flux');
INSERT INTO marca(id, descricao) VALUES (159, 'Toad');
INSERT INTO marca(id, descricao) VALUES (160, 'Puff');
INSERT INTO marca(id, descricao) VALUES (161, 'Puff 2 Gomos');
INSERT INTO marca(id, descricao) VALUES (162, 'Bits');
INSERT INTO marca(id, descricao) VALUES (163, 'Chester');
INSERT INTO marca(id, descricao) VALUES (164, 'Chester Redondo');
INSERT INTO marca(id, descricao) VALUES (165, 'Iô');
INSERT INTO marca(id, descricao) VALUES (166, 'Rocca');
INSERT INTO marca(id, descricao) VALUES (167, 'Sama');
INSERT INTO marca(id, descricao) VALUES (168, 'Ankur');
INSERT INTO marca(id, descricao) VALUES (169, 'Emocion');
INSERT INTO marca(id, descricao) VALUES (170, 'Galileu');
INSERT INTO marca(id, descricao) VALUES (171, 'Lázaro');
INSERT INTO marca(id, descricao) VALUES (172, 'Master');
INSERT INTO marca(id, descricao) VALUES (173, 'Matteo CV');
INSERT INTO marca(id, descricao) VALUES (174, 'Nowe');
INSERT INTO marca(id, descricao) VALUES (175, 'Ren');
INSERT INTO marca(id, descricao) VALUES (176, 'Shizen');
INSERT INTO marca(id, descricao) VALUES (177, 'Interim');
INSERT INTO marca(id, descricao) VALUES (178, 'Readme');
INSERT INTO marca(id, descricao) VALUES (179, 'Taiko');
INSERT INTO marca(id, descricao) VALUES (180, 'Uno');
INSERT INTO marca(id, descricao) VALUES (181, 'Breve');
INSERT INTO marca(id, descricao) VALUES (182, 'Aloha');
INSERT INTO marca(id, descricao) VALUES (183, 'Cíntia');
INSERT INTO marca(id, descricao) VALUES (184, 'Equilíbrio Base Tecido');
INSERT INTO marca(id, descricao) VALUES (185, 'Equilíbrio Base Laminado');
INSERT INTO marca(id, descricao) VALUES (186, 'Lasso');
INSERT INTO marca(id, descricao) VALUES (187, 'Eixo');
INSERT INTO marca(id, descricao) VALUES (188, 'Órbita');
INSERT INTO marca(id, descricao) VALUES (189, 'Fuji Simétrica');
INSERT INTO marca(id, descricao) VALUES (190, 'Ranhura');
INSERT INTO marca(id, descricao) VALUES (191, 'Brooklin');
INSERT INTO marca(id, descricao) VALUES (192, 'Gordon');
INSERT INTO marca(id, descricao) VALUES (193, 'Hiato');
INSERT INTO marca(id, descricao) VALUES (194, 'Hoyo');
INSERT INTO marca(id, descricao) VALUES (195, 'Isao');
INSERT INTO marca(id, descricao) VALUES (196, 'KSA');
INSERT INTO marca(id, descricao) VALUES (197, 'Move');
INSERT INTO marca(id, descricao) VALUES (198, 'Pensil');
INSERT INTO marca(id, descricao) VALUES (199, 'Poncho');
INSERT INTO marca(id, descricao) VALUES (200, 'Saints');
INSERT INTO marca(id, descricao) VALUES (201, 'Urupê');
INSERT INTO marca(id, descricao) VALUES (202, 'Vinge');
INSERT INTO marca(id, descricao) VALUES (203, 'Hana');
INSERT INTO marca(id, descricao) VALUES (204, 'Mochi');
INSERT INTO marca(id, descricao) VALUES (205, 'Vinco');
INSERT INTO marca(id, descricao) VALUES (206, 'Constance Redondo');
INSERT INTO marca(id, descricao) VALUES (207, 'Constance Oval');
INSERT INTO marca(id, descricao) VALUES (208, 'Contance Banco');
INSERT INTO marca(id, descricao) VALUES (209, 'Landon');
INSERT INTO marca(id, descricao) VALUES (210, 'Poggio');
INSERT INTO marca(id, descricao) VALUES (211, 'Banco Dobra');
INSERT INTO marca(id, descricao) VALUES (212, 'Aime');